export enum Handling {
    BLANKETT = 'BLANKETT',
    JOURNALFØR = 'JOURNALFØR',
    SAKSBEHANDLE = 'SAKSBEHANDLE',
    JOURNALFØR_MIGRERING = 'JOURNALFØR_MIGRERING',
    TILBAKE = 'TILBAKE',
    INGEN = 'INGEN',
}
