export enum Handling {
    JOURNALFØR = 'JOURNALFØR',
    SAKSBEHANDLE = 'SAKSBEHANDLE',
    TILBAKE = 'TILBAKE',
    KLAGE = 'KLAGE',
    INGEN = 'INGEN',
    BEHANDLINGSOVERSIKT = 'BEHANDLINGSOVERSIKT',
}
