#!/bin/bash

kubectl config use-context dev-gcp

function get_secrets() {
  local repo=$1
  kubectl -n teamfamilie get secret ${repo} -o json | jq '.data | map_values(@base64d)'
}

EF_SAK_FRONTEND_LOKAL_SECRETS=$(get_secrets azuread-familie-ef-sak-frontend-lokal)

AZURE_APP_CLIENT_ID=$(echo "$EF_SAK_FRONTEND_LOKAL_SECRETS" | jq -r '.AZURE_APP_CLIENT_ID')
AZURE_APP_CLIENT_SECRET=$(echo "$EF_SAK_FRONTEND_LOKAL_SECRETS" | jq -r '.AZURE_APP_CLIENT_SECRET')
AZURE_APP_WELL_KNOWN_URL=$(echo "$EF_SAK_FRONTEND_LOKAL_SECRETS" | jq -r '.AZURE_APP_WELL_KNOWN_URL')
AZURE_OPENID_CONFIG_ISSUER=$(echo "$EF_SAK_FRONTEND_LOKAL_SECRETS" | jq -r '.AZURE_OPENID_CONFIG_ISSUER')
AZURE_OPENID_CONFIG_JWKS_URI=$(echo "$EF_SAK_FRONTEND_LOKAL_SECRETS" | jq -r '.AZURE_OPENID_CONFIG_JWKS_URI')
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT=$(echo "$EF_SAK_FRONTEND_LOKAL_SECRETS" | jq -r '.AZURE_OPENID_CONFIG_TOKEN_ENDPOINT')
AZURE_APP_JWK=$(echo "$EF_SAK_FRONTEND_LOKAL_SECRETS" | jq -r '.AZURE_APP_JWK')

if [ -z "$AZURE_APP_CLIENT_ID" ] || [ -z "$AZURE_APP_CLIENT_SECRET" ]; then
  echo "Klarte ikke å hente hemmeligheter. Er du logget in med NAIS eller NAIS login?"
  return 1
fi

# Skriver variabler til .env fil.
cat << EOF > .env
AZURE_APP_CLIENT_ID='$AZURE_APP_CLIENT_ID'
AZURE_APP_CLIENT_SECRET='$AZURE_APP_CLIENT_SECRET'
AZURE_APP_WELL_KNOWN_URL='$AZURE_APP_WELL_KNOWN_URL'
AZURE_OPENID_CONFIG_ISSUER='$AZURE_OPENID_CONFIG_ISSUER'
AZURE_OPENID_CONFIG_JWKS_URI='$AZURE_OPENID_CONFIG_JWKS_URI'
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT='$AZURE_OPENID_CONFIG_TOKEN_ENDPOINT'
AZURE_APP_JWK='$AZURE_APP_JWK'

# Local environment
ENV=lokalt-mot-preprod
EOF