apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      replyURLs:
      {{#each ingresses as |url|}}
        - {{url}}/auth/openid/callback
      {{/each}}
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-sak-frontend-redis
      external:
        {{#each externals as |host|}}
        - host: {{host}}
        {{/each}}
  envFrom:
    - secret: familie-ef-sak-frontend
  env:
    - name: APP_VERSION
      value: "{{version}}"
    - name: REDIS_HOST
      value: familie-ef-sak-frontend-redis
    {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}