apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak-frontend
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  istio:
    enabled: false
  ingresses:
    - https://ensligmorellerfar.dev-fss.nais.io
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/familie-ef-sak-frontend/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /azuread/data/dev/creds/familie-ef-sak-frontend
        mountPath: /var/run/secrets/nais.io/azuread
  webproxy: true
  env:
    - name: APP_VERSION
      value: "{{version}}"
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
