apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak-frontend
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: navikt/familie-ef-sak-frontend:{{version}}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  istio:
    enabled: false
  ingresses:
    - https://familie-ef-sak-frontend.nais.adeo.no
    - https://alenemedbarn.nais.adeo.no
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/familie-ef-sak-frontend/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /azuread/data/prod/creds/familie-ef-sak-frontend
        mountPath: /var/run/secrets/nais.io/azuread
  webproxy: true
  env:
    - name: APP_VERSION
      value: "{{version}}"
    - name: CLIENT_ID
      value: /run/secrets/nais.io/azuread/client_id
    - name: CLIENT_SECRET
      value: /run/secrets/nais.io/azuread/client_secret
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
