apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  azure:
    application:
      enabled: true
      replyURLs:
      {{#each ingresses as |url|}}
        - {{url}}/auth/openid/callback
      {{/each}}
      claims:
        groups:
        {{#each claimGroups as |group|}}
          - id: {{group}}
        {{/each}}
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-sak-frontend-redis
        - application: familie-brev
      external:
        {{#each externals as |host|}}
        - host: {{host}}
        {{/each}}
  envFrom:
    - secret: familie                       # Henter ut EF_SAK_SCOPE
    - secret: familie-ef-sak-frontend-redis # Henter ut REDIS_PASSWORD
    - secret: familie-ef-sak-frontend       # Ulike secrets
  env:
    - name: APP_VERSION
      value: "{{version}}"
    - name: ENV
      value: "{{envEnv}}"
