export interface Revurderingsinformasjon {
    kravMottatt: string;
    årsakRevurdering: ÅrsakRevurdering;
}

export interface ÅrsakRevurdering {
    årsak: Årsak;
    opplysningskilde: Opplysningskilde;
    beskrivelse?: string;
}

export enum Årsak {
    ENDRING_INNTEKT = 'ENDRING_INNTEKT',
    ENDRING_AKTIVITET = 'ENDRING_AKTIVITET',
    ENDRING_INNTEKT_OG_AKTIVITET = 'ENDRING_INNTEKT_OG_AKTIVITET',

    SØKNAD_UTVIDELSE_UTDANNING = 'SØKNAD_UTVIDELSE_UTDANNING',
    SØKNAD_UTVIDELSE_SÆRLIG_TILSYNSKREVENDE_BARN = 'SØKNAD_UTVIDELSE_SÆRLIG_TILSYNSKREVENDE_BARN',
    SØKNAD_FORLENGELSE_FORBIGÅENDE_SYKDOM = 'SØKNAD_FORLENGELSE_FORBIGÅENDE_SYKDOM',
    SØKNAD_FORLENGELSE_PÅVENTE_AKTIVITET = 'SØKNAD_FORLENGELSE_PÅVENTE_AKTIVITET',
    SØKNAD_NY_PERIODE_NYTT_BARN = 'SØKNAD_NY_PERIODE_NYTT_BARN',
    SØKNAD_NYTT_BGH_SKOLEÅR = 'SØKNAD_NYTT_BGH_SKOLEÅR',
    SØKNAD_NYTT_SKOLEÅR = 'SØKNAD_NYTT_SKOLEÅR',

    OPPHØR_VILKÅR_IKKE_OPPFYLT = 'OPPHØR_VILKÅR_IKKE_OPPFYLT',
    OPPHØR_EGET_ØNSKE = 'OPPHØR_EGET_ØNSKE',

    ENDRING_STØNADSPERIODE = 'ENDRING_STØNADSPERIODE',
    SØKNAD_NY_PERIODE_HOVEDPERIODE_IKKE_BRUKT_OPP_TIDLIGERE = 'SØKNAD_NY_PERIODE_HOVEDPERIODE_IKKE_BRUKT_OPP_TIDLIGERE',
    SØKNAD_BRUKT_OPP_HOVEDPERIODEN_TIDLIGERE = 'SØKNAD_BRUKT_OPP_HOVEDPERIODEN_TIDLIGERE',
    SØKNAD_ETTER_AVSLAG = 'SØKNAD_ETTER_AVSLAG',
    SØKNAD_ETTER_OPPHØR = 'SØKNAD_ETTER_OPPHØR',

    ENDRING_TILSYNSUTGIFTER = 'ENDRING_TILSYNSUTGIFTER',
    ENDRING_ANTALL_BARN = 'ENDRING_ANTALL_BARN',
    ENDRING_UTGIFTER_SKOLEPENGER = 'ENDRING_UTGIFTER_SKOLEPENGER',

    SANKSJON_1_MÅNED = 'SANKSJON_1_MÅNED',
    UTESTENGELSE = 'UTESTENGELSE',
    ANNET = 'ANNET',
    KLAGE_OMGJØRING = 'KLAGE_OMGJØRING',
    ANKE_OMGJØRING = 'ANKE_OMGJØRING',
}

export enum Opplysningskilde {
    MELDING_MODIA = 'MELDING_MODIA',
    INNSENDT_DOKUMENTASJON = 'INNSENDT_DOKUMENTASJON',
    BESKJED_ANNEN_ENHET = 'BESKJED_ANNEN_ENHET',
    LIVSHENDELSER = 'LIVSHENDELSER',
    OPPLYSNINGER_INTERNE_KONTROLLER = 'OPPLYSNINGER_INTERNE_KONTROLLER',
}
