name: Build, push, and deploy app to dev

on:
  push:
    branches-ignore:
      - 'master'
  workflow_dispatch:
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/familie-ef-sak-frontend:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        env:
          GIT_BRANCH_NAME: ${{ github.ref }}
        run: echo "GIT_BRANCH_NAME=${GIT_BRANCH_NAME#refs/heads/}" >> $GITHUB_ENV
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT_DATE: ${{ github.event.head_commit.timestamp }}
        run: |
          yarn
          yarn build
          docker build . -t ${IMAGE}
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: build_n_deploy/naiserator/naiserator_dev.yaml