apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak-frontend-redis
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: bitnami/redis:6.0.10
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1
  resources: # you need to monitor need your self
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak-frontend
        - application: familie-ef-sak-frontend-redisexporter
  envFrom:
    - secret: familie-ef-sak-frontend-redis